start section products
demetrx/ice-cream pull request #4
Opened 2022-01-14 18:38 UTC by Tatianayarchenko

начала делать разметку со стилями

2022-01-14 19:46 UTC, demetrx requested changes
Давай по BEMу сделаем, чтоб все одинаково)

2022-01-15 15:47 UTC, Tatianayarchenko commented
добавила картинки и переименовала классы по ВЕМ

2022-01-15 20:48 UTC, Tatianayarchenko commented
попробовала сделать описание продукта при открытии кнопки, пока не получается, закинула черновик, на всякий случай.

2022-01-16 08:55 UTC, demetrx approved these changes

2022-01-16 08:55 UTC, merged