section advantages start
demetrx/ice-cream pull request #6
Opened 2022-01-14 19:26 UTC by SvetlanaSavka

2022-01-14 19:30 UTC, SvetlanaSavka commented
- немає на третю картинку формату (2х)  секція advantages;
- зявляється точка перелому в діапазоні 541-767 не розумію через що саме?

2022-01-14 20:10 UTC, demetrx requested changes
Всё классно, но названия классов не совсем по BEM. advantages__list, advantages__item, advantages__text - что-то такое, блок__елемент--модификатор. Так как ты, говорили, не желательно делать( Просмотри конспект. И h1 на английском. Сорян, что достаю. Просто лучше сейчас исправить

2022-01-14 20:10 UTC, demetrx commented on src/partials/advantages.html
> +        <h1 class="visually-hidden">Преимущества</h1>
У нас сайт на английском, но тут ты на русском скрыла)))

2022-01-15 12:48 UTC, demetrx approved these changes

2022-01-15 12:48 UTC, merged